### ISSUE TITLE
Features required for an initial marketplace release.

### ISSUE THREAD

**Issue by thegecko** [eclipse-cdt-cloud/vscode-memory-inspector#27]
I believe there are a few items which make this extension usable enough for an initial release:

- [x] The ability to page backwards and forwards through memory (perhaps exposing a page size setting) #17 
- [x] The ability to persist the settings/config (e.g. which columns are visible) #34
- [x] Some UI polish for the settings area, perhaps a popover? #40 

cc @colin-grant-work

**Comment by thegecko** [comment]
I think the columns are a personal preference, personally.

**Comment by kenneth-marut-work** [comment]
@thegecko could you clarify what you mean by 
>Some UI polish for the settings area, perhaps a popover?

thanks :)

**Comment by sophewilliams** [comment]
Would this work?
![Screenshot 2023-09-07 at 10 02 12](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/26062437/8e9f999f-982a-40e5-a8e7-1f4dc6441253)

**Comment by thegecko** [comment]
Thanks @sophewilliams , @kenneth-marut-work would you be able to implement that as a popup when the settings button is pressed?

**Comment by sophewilliams** [comment]
@kenneth-marut-work Hello! Just a note on the design - I've used our own design system as that's what I have to hand, but hopefully it can be implemented using VSCode UI elements and visual style.

**Comment by colin-grant-work** [comment]
The mockup looks great - more compact than the current version, certainly - but it doesn't look like it would bring a material change in the user flow for adjusting the view settings. I'm not entirely opposed to a change, but I don't think I'd consider implementing a new style a blocker for release, and I even have a slight preference for retaining the current implementation for continuity, unless a new version definitely improves the experience.

**Comment by sophewilliams** [comment]
Do users need to continually adjust these settings?

**Comment by colin-grant-work** [comment]
> Do users need to continually adjust these settings?

Likely not, but they may want to fiddle with them a bit (esp. the grouping settings) before settling on what suits their interests and current display size best, so I think being able to do that while also seeing the view is useful.

**Comment by thegecko** [comment]
Without the need for persistence, the popover design should offer a design which stays out of the users way.

@sophewilliams I know you are often keen to get feedback from users anyway and iterate on any design. Do you have a strong preference which design we should start with?

**Comment by sophewilliams** [comment]
@thegecko I don't have a strong preference, but I'm always in favour of doing the least amount of work possible before getting feedback. That could mean sticking with the current design but it needs to be tweaked to follow usability best practice (we don't want to get feedback on the obvious stuff). I'll outline the changes and you can decide on the feasibility of both options:

- the settings should be directly beneath the hide/show settings button
- the settings need to be visually distinct from the rest of the layout (i.e. a line separator or background colour)
- checkboxes should be used for selecting the columns to view, and these are easier to use when vertically stacked
- the `Bytes per group` and `Group per row` selectors should be number pickers - user can type in or use increase/decrease buttons to toggle

Hope that's helpful :)

**Comment by kenneth-marut-work** [comment]
> the Bytes per group and Group per row selectors should be number pickers - user can type in or use increase/decrease buttons to toggle

Regarding the above, just want to point out the UI elements that we have available to us with the VSCode webview toolkit [here](https://github.com/microsoft/vscode-webview-ui-toolkit)

I don't believe there is a native number incrementor input (and not sure I've seen one throughout the UI either, but correct me if I'm wrong) and the bytes per group/groups per row have fixed values (i.e. powers of two, hence the dropdown).

**Comment by sophewilliams** [comment]
> the bytes per group/groups per row have fixed values (i.e. powers of two, hence the dropdown)

Ah, okay then a dropdown or radio buttons is fine.

They don't seem to have a number incrementor, so perhaps all we can do for now is lessen the width of the dropdown so it's easier to scan and interact with, and sets expectations around the affordance it provides. What's the limit of the number of groups per row (if there is one)?

**Comment by kenneth-marut-work** [comment]
> > the bytes per group/groups per row have fixed values (i.e. powers of two, hence the dropdown)
> 
> Ah, okay then a dropdown or radio buttons is fine.
> 
> They don't seem to have a number incrementor, so perhaps all we can do for now is lessen the width of the dropdown so it's easier to scan and interact with, and sets expectations around the affordance it provides. What's the limit of the number of groups per row (if there is one)?

Here are the options for wordsPerGroup (renamed from bytesPerGroup) & groupsPerRow

![image](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/62660714/9071ad5f-17cf-4280-82eb-ce9f7439d46b)

**Comment by thegecko** [comment]
I've asked one of our engineers to implement this settings UI so we can discuss on a PR, cc @arekzaluski

**Comment by arekzaluski** [comment]
Here is the current UX design for it:

![memoryInspector](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/13417215/3ebf7168-bb9f-4b55-9d8e-c89f08b1953e)

**Comment by thegecko** [comment]
Thanks @arekzaluski. Once we have agreement on that PR I think we are good to got for an initial release!

**Comment by arekzaluski** [comment]
I took also the liberty of fixing one other small UI issue: https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/42

**Comment by thegecko** [comment]
I think we are ready for an initial release. @colin-grant-work are you happy for this to happen? Shall we go for v1.0.0?

**Comment by colin-grant-work** [comment]
No objections here. I do think 1.0 would be the right move. It's a bit annoying when people stick on pre-release-style versions forever.

**Comment by thegecko** [comment]
Please see #43

**Comment by thegecko** [comment]
Initial release made!

https://open-vsx.org/extension/eclipse-cdt/memory-inspector

https://marketplace.visualstudio.com/items?itemName=eclipse-cdt.memory-inspector
