### ISSUE TITLE
Memory Inspector usability enhancements

### ISSUE THREAD

**Issue by jreineckearm** [eclipse-cdt-cloud/vscode-memory-inspector#49]
As discussed during the last CDT Cloud meeting, I'd like to share some thoughts on potential usability enhancements for the Memory Inspector.
- [x] Refresh window contents when pressing pressing Enter in Address, Offset, Length fields (see [#57](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/57))
- [x] Keep the options section visible when scrolling (see [#57](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/57))
- [x] https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/60
- [x] https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/70
- [x] https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/71
- [x] Ensure/verify expressions in address fields are sent to debug adapter as is.
- [x] https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/61
- [x] Dynamically grow scrollbar/displayed range when reaching end of view instead of the need to click "Load more bytes below" (Extracted into https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/56)
- [x] https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/91

**Comment by planger** [comment]
@jreineckearm regarding *Ensure/verify expressions in address fields are sent to debug adapter as is.*:
Imho this seems to work fine:

https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/588090/8cb29efe-6b3e-4f7e-821b-321a16be0568

Can we tick that off?

**Comment by jreineckearm** [comment]
Thanks for double-checking that! Was briefly puzzled by the effective address change. But that actually is another indicator that it works well because the back-end expression engine successfully applied pointer arithmetic in this case. :-)
I'll tick that item off.

**Comment by jreineckearm** [comment]
I think this epic issue is good to get closed.
Thanks to everyone involved in making these changes happen: @planger , @martin-fleck-at , @colin-grant-work , @haydar-metin !
