### ISSUE TITLE
EPIC: Feature Parity with Theia Extension

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-cdt-cloud/vscode-memory-inspector#5]
**Description**

- Improve handling of debug session lifecycle
    - [x] Track capabilities of created sessions
    - [x] Set context based on active session
    - [x] Check capabilities of active session
    - [ ] Handle capability events?
    - [ ] Link view and session?
- Improve View
    - [x] Use monospace in view.
    - [ ] Implement change marking.
    - [ ] Copy paste should produce a grid, not a vertical list.
    > Can't use VSCode Grid components for this, [at least for now](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/374).
    - [ ] Implement hover.
- Implement Configuration Widget
- Implement Diffing
- Implement Memory Write UI
- Implement Memory Search UI
- Implement Variable Handling
    - [ ] Option for full resolution (incl. sizes) vs. marking start
- Implement Data Breakpoint UI
- Implement Register View?
    - [ ] Register + memory linkage to show registers pointing at memory regions?
> Since registers are supposed to be handled in the variables request, maybe there's no need for a separate view in the Memory Inspector? Are there areas where we can go beyond the presentation in the Variables Widget?
- Implement Contribution System?
> Idea here would be to identify behavior that differs among adapters and let plugins that contribute debuggers also modify Memory Inspector behavior. Some areas that might differ: resolving variable sizes or internal structure, memory searchability, variable reference syntax (though the memory reference field of the DAP mostly covers that).

**Comment by colin-grant-work** [comment]
I will also create issues for the other smaller parts so that they can be handled individually.
