### ISSUE TITLE
Memory Inspector context menu enhancements

### ISSUE THREAD

**Issue by jreineckearm** [eclipse-cdt-cloud/vscode-memory-inspector#51]
**Description**

The current Memory Inspector context menu seems to be the standard context menu. It would be very useful to utilize it for a couple of usability enhancements.
- [x] Copy selection #94 
- [x] Allow contributions from other extensions, for example to send selected data to other views #94
- [x] Quick access to memory window configurations #94 
    * Display format
    * Words per group
    * Groups per row
    * Physical access size
    * Show variables column
    * Show ASCII
- [x] Load/Save (will be covered by PR for #50)
- [X] Set data breakpoint: Extracted to https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/102

**Additional information**

**Comment by tortmayr** [comment]
The following is covered by https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/94
- Copy selection
- Quick access to memory window configurations
- Allow contributions from other extensions, for example to send selected data to other views

(I cannot update the original issue description)

**Comment by planger** [comment]
@martin-fleck-at Can this issue be already closed? I think all linked PRs are merged, aren't they?

**Comment by martin-fleck-at** [comment]
@planger Yes, I think it can. I'm just not allowed to check the items in the description ;-)

**Comment by colin-grant-work** [comment]
Fixed by #94 and #96.
